[package]
name = "cosmology"
author = "cavemanloverboy"
repository = "https://github.com/cavemanloverboy/cosmology"
version = "0.1.1"
edition = "2021"
license = "MIT"
keywords = ["cosmology", "physics", "astrophysics", "universe", "structure"]
categories = ["science"]
description = "An early-in-development crate aiming to provide a lot of utilities commonly used in cosmology."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
colossus-python = ["pyo3"]

[dependencies]
quadrature = "0.1.2"


# Optional testing dependency!
# We used colossus==1.3.1 for testing
[dependencies.pyo3]
version = "0.16.5"
features = ["auto-initialize"]
optional = true

[dev-dependencies]
plotters = "0.3.1"
concat-idents = "1.1.3"
